fiche_index:
    path:     /
    defaults: { _controller: "AppBundle:Fiche:index" }
    methods:  GET

fiche_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Fiche:show" }
    methods:  GET

fiche_new:
    path:     /new
    defaults: { _controller: "AppBundle:Fiche:new" }
    methods:  [GET, POST]

fiche_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Fiche:edit" }
    methods:  [GET, POST]

fiche_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Fiche:delete" }
    methods:  DELETE
