<?php

namespace AppBundle\Repository;

/**
 * TestEntiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestEntiteRepository extends \Doctrine\ORM\EntityRepository
{
}
