AppBundle\Entity\Manager:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ManagerRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        firstName:
            type: string
            length: 255
        lastName:
            type: string
            length: 255
        title:
            type: string
            length: 255
    oneToMany:
      fiches:
        targetEntity: Fiche
        mappedBy: manager
    lifecycleCallbacks: {  }
